/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonAliyun: typeof import('./src/components/ButtonAliyun.vue')['default']
    ButtonQuark: typeof import('./src/components/ButtonQuark.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    copy: typeof import('./src/components/ButtonAliyun copy.vue')['default']
    PreviewEntry: typeof import('./src/components/PreviewEntry.vue')['default']
    PreviewPanel: typeof import('./src/components/PreviewPanel.vue')['default']
  }
}
