/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button123: typeof import('./src/components/Button123.vue')['default']
    ButtonAliyun: typeof import('./src/components/ButtonAliyun.vue')['default']
    ButtonBaidu: typeof import('./src/components/ButtonBaidu.vue')['default']
    ButtonCmcc: typeof import('./src/components/ButtonCmcc.vue')['default']
    ButtonEsurfing: typeof import('./src/components/ButtonEsurfing.vue')['default']
    ButtonQuark: typeof import('./src/components/ButtonQuark.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    PreviewEntry: typeof import('./src/components/PreviewEntry.vue')['default']
    PreviewPanel: typeof import('./src/components/PreviewPanel.vue')['default']
  }
}
