name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drive-rename.user.js
          path: dist/drive-rename.user.js

      - name: Generate changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/drive-rename.user.js
          tag: ${{ github.ref }}
          overwrite: false
